module.exports = {

	E_NO_CONFIG: 1,
	E_NO_SAP_SYSTEMS: 2,
	E_NO_DEFAULT_SAP_SYSTEM: 3,
	E_DEFAULT_SAP_SYSTEM_NO_EXISTS: 4,
	E_INVALID_SAP_SYSTEM: 5,
	E_NO_HTTP_CONFIG: 6,
	E_NO_HTTP_PORT: 7,
	E_NO_HTTPS_CONFIG: 8,
	E_NO_HTTPS_PORT: 9,
	E_NO_JWT_CONFIG: 10,
	E_JWT_NO_SIGN_KEY: 11,
	E_JWT_NO_ENC_KEY: 12,
	E_NO_MDB_CONFIG: 13,
	E_MDB_NO_HOSTS: 14,
	E_MDB_NO_USER: 15,
	E_MDB_NO_PASS: 16,
	E_MDB_NO_DATABASE: 17,
	E_NO_SQLITE_CONFIG: 18,
	E_SQLITE_NO_PATH: 19,



	E_KEY_OR_CERT_NOT_FOUND: 50,
	E_HTTP_SERVER_ERROR: 51,
	E_HTTPS_SERVER_ERROR: 52


}
