module.exports = {

	OK: 0,
	RECEPCIONADO: 1,
	ESPERANDO_INCIDENCIAS: 2,
	INCIDENCIAS_RECIBIDAS: 3,
	ESPERANDO_NUMERO_PEDIDO: 4,
	DESCARTADO: 5,
	FALLO_AUTENTICACION: 6,
	PETICION_INCORRECTA: 7,
	NO_SAP: 8
};
